name: Check

on:
  push:
    branches: [ "main" ]
    tags-ignore: [ "**" ]
  pull_request:


jobs:
  gotest:
    strategy:
      matrix:
        go-version: [1.23.x]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Run tests
        run: go test -race ./...